### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by joshuarubin** [joshuarubin/zb#11]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x5b9d39]

goroutine 19 [running]:
jrubin.io/zb/lib/dependency.(*Target).key(0xc420497ab0, 0x8d8800, 0xc42012e850)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/dependency/target.go:62 +0x29
jrubin.io/zb/lib/dependency.(*Targets).existsNoLock(0xb47480, 0xc420497ab0, 0x300000002, 0x0)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/dependency/target.go:123 +0x3c
jrubin.io/zb/lib/dependency.(*Targets).insertNoLock(0xb47480, 0xc420497ab0, 0x8d8800)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/dependency/target.go:96 +0x39
jrubin.io/zb/lib/dependency.(*Targets).Insert(0xb47480, 0xc420497ab0, 0xc420497a01)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/dependency/target.go:90 +0x4e
jrubin.io/zb/lib/dependency.NewTarget(0x0, 0x0, 0xc42012e850, 0xc420497a40)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/dependency/target.go:50 +0x6f
jrubin.io/zb/lib/project.(*Package).Targets(0xc4201335c0, 0xb13820, 0xb47b60, 0xb46910, 0xb46900, 0x0, 0xc42011e580, 0x17, 0x0, 0xc420130820, ...)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/project/package.go:120 +0x327
jrubin.io/zb/lib/project.Packages.targets.func1(0x8, 0x9124d0)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/lib/project/packages.go:68 +0x94
jrubin.io/zb/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4201f96c0, 0xc4201354a0)
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by jrubin.io/zb/vendor/golang.org/x/sync/errgroup.(*Group).Go
    /home/michael/code/go-thirdparty/src/jrubin.io/zb/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x66
```

**Comment by joshuarubin** [comment]
cc: @michaeltrobinson
