### ISSUE TITLE
Test command raises panic

### ISSUE THREAD

**Issue by Taik** [joshuarubin/zb#9]
Seeing if anyone else got this issue when running `zb test`.

```bash
$ zb test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13fae2]

goroutine 1 [running]:
panic(0x444000, 0xc420014120)
        /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
jrubin.io/zb/lib/project.(*Package).Hash(0x0, 0xc4204f8450, 0xc420422ab1, 0x25, 0x71e7e0)
        /Users/thinh/go/src/jrubin.io/zb/lib/project/package.go:280 +0x42
jrubin.io/zb/lib/project.(*Package).TestHash(0xc4202c6d90, 0xc42015a788, 0x1432a0, 0xc420377550, 0x0, 0x1)
        /Users/thinh/go/src/jrubin.io/zb/lib/project/package.go:259 +0x50a
jrubin.io/zb/lib/zbtest.(*ZBTest).CacheFile(0xc42015a780, 0xc4202c6d90, 0x1, 0x0, 0x0, 0x0)
        /Users/thinh/go/src/jrubin.io/zb/lib/zbtest/zbtest.go:37 +0x53
jrubin.io/zb/lib/zbtest.(*ZBTest).HaveResult(0xc42015a780, 0xc4202c6d90, 0xc420313501, 0x35, 0xc420377610)
        /Users/thinh/go/src/jrubin.io/zb/lib/zbtest/zbtest.go:55 +0x48
jrubin.io/zb/cmd/test.(*cc).buildPackagesLists(0xc42015a780, 0xc42014f500, 0x6, 0x8, 0xc4200335a8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/thinh/go/src/jrubin.io/zb/cmd/test/test.go:111 +0x108
jrubin.io/zb/cmd/test.(*cc).buildProjectsLists(0xc42015a780, 0xc420032408, 0x1, 0x1, 0xc420032408, 0x1, 0x1, 0x0, 0x0, 0x1e, ...)
        /Users/thinh/go/src/jrubin.io/zb/cmd/test/test.go:126 +0xc9
jrubin.io/zb/cmd/test.(*cc).runProjects(0xc42015a780, 0x6d3f80, 0xc420032010, 0xc42000c0a0, 0x6, 0x6, 0xc42013dc00, 0xc42009c000, 0xc420051808, 0xccbf1, ...)
        /Users/thinh/go/src/jrubin.io/zb/cmd/test/test.go:99 +0x98
jrubin.io/zb/cmd/test.(*cc).run(0xc42015a780, 0x6d3f80, 0xc420032010, 0xc42000c0a0, 0x6, 0x6, 0xc42013dc00, 0x0)
        /Users/thinh/go/src/jrubin.io/zb/cmd/test/test.go:66 +0x2f0
jrubin.io/zb/cmd/test.(*cc).New.func1(0xc420174140, 0x0, 0x702200)
        /Users/thinh/go/src/jrubin.io/zb/cmd/test/test.go:37 +0x6c
main.wrapFn.func1(0xc420174140, 0x0, 0xc420174140)
        /Users/thinh/go/src/jrubin.io/zb/wrap.go:33 +0x33
jrubin.io/zb/vendor/github.com/urfave/cli.HandleAction(0x42df60, 0xc42013cd50, 0xc420174140, 0xc420074b00, 0x0)
        /Users/thinh/go/src/jrubin.io/zb/vendor/github.com/urfave/cli/app.go:483 +0xb9
jrubin.io/zb/vendor/github.com/urfave/cli.Command.Run(0x4c18a5, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4da8df, 0x46, 0x0, ...)
        /Users/thinh/go/src/jrubin.io/zb/vendor/github.com/urfave/cli/command.go:193 +0xb96
jrubin.io/zb/vendor/github.com/urfave/cli.(*App).Run(0xc42008d520, 0xc42000c080, 0x8, 0x8, 0x0, 0x0)
        /Users/thinh/go/src/jrubin.io/zb/vendor/github.com/urfave/cli/app.go:250 +0x812
main.main()
        /Users/thinh/go/src/jrubin.io/zb/main.go:110 +0x51
```

**Comment by joshuarubin** [comment]
I think I fixed this. Can you try again with the new source? If it still fails, can you please give me your `$GOPATH` and repo file structure?

**Comment by Taik** [comment]
Thanks for fixing it--just tested with latest source and error is gone.
